routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index');
Auth::routes();
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('Users', 'usersController');
    Route::resource('Settings','SettingController');
    Route::resource('About','AboutController');
    Route::resource('Statistic','StatisticController');
    Route::resource('Quote','QuoteController');
    Route::resource('Slider','SliderController');
    Route::resource('Contact','ContactController');
    Route::View('/','home')->name('dashboard');
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable=[
        'name', 'email', 'subject', 'read_at', 'reply', 'user_id', 'message',
    ];

    public static $rules=[
        'name'=>'required|string|max:191',
        'email'=>'required|email|max:191',
        'subject'=>'required|string|max:191',
        'reply'=>'nullable|string',
        'message'=>'required|string',
    ];
    public static $updateRules=[
        'reply'=>'required|string',
    ];

    public function created_by(){
        return $this->belongsTo('App\User','user_id');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Contacts = Contact::all();
        return View('admin.Contact.index', compact('Contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
  /*  public function create()
    {
        return view('admin.Contact.create');
    }*/

 /*   public function store(Request $request)
    {
        $requests=$request->validate(Contact::$rules);
        $requests['user_id']=Auth::id();
        Contact::create($requests);
        return redirect()->route('Contact.index');
    }*/

    public function show(Contact $Contact)
    {


    }

    public function edit($id)
    {
        $Contact= Contact::find($id);
        $Contact->fill(['read_at'=>Carbon::today()])->save();
        return view('admin.Contact.edit',compact('Contact'));
    }
    public function update(Request $request, $id)
    {
        $Contact=Contact::find($id);
        $requests=$request->validate(Contact::$updateRules);
        $Contact->fill($requests)->save();
        return redirect()->route('Contact.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $Contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Contact=  Contact::find($id);
        if(is_null($Contact)){
            return back()->with('error','هذا الموضوع غير موجود');
        }
        $Contact->delete();
        return back()->with('success','تم الحذف ');
    }
}

resources/views/admin/Contact/_form.blade.php
<div class="form-body">


    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('email') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('email',old('email'),['class'=>'form-control','disabled'])!!}
        <label for="form_control_1">الموضوع البريد الالكترونى</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('name') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('name',old('name'),['class'=>'form-control','disabled'])!!}
        <label for="form_control_1">الموضوع البريد الالكترونى</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('subject') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('subject',old('subject'),['class'=>'form-control','disabled'])!!}
        <label for="form_control_1">الموضوع</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label">
        {!!Form::textarea('message',Null,['class'=>'form-control','disabled'])!!}
        <label for="form_control_1">الرساله</label>
    </div>

    <div class="form-group form-md-line-input form-md-floating-label {{ $errors->has('reply') ? ' has-error' : 'has-success' }} ">
        {!!Form::textarea('reply',old('reply'),['class'=>'form-control summernote'])!!}
        <label for="form_control_1">الرد</label>
    </div>

    <div class="form-actions noborder">
        <button type="submit" class="btn blue">حفظ</button>
        <button type="reset" class="btn default">الغاء</button>
    </div>
</div>

resources/views/admin/Contact/_table.blade.php
<table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_3" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th class="all  text-center"> الاسم</th>
        <th class="all  text-center">الموضوع</th>
        <th class="all  text-center">البريد الالكترونى</th>
        <th class="min-phone-l  text-center">الرساله</th>
        <th class="min-phone-l  text-center">الرد</th>
        <th class="min-phone-l  text-center">الاعدادت</th>
    </tr>
    </thead>
    <tbody>
    @foreach($Contacts as $Contact)
        <tr>
           <td> {!! $Contact->name !!} </td>
            <td>{!!$Contact->subject!!}</td>
            <td> <a href="mailto:{!! $Contact->email !!}?Subject={!! $Contact->subject !!}" target="_top">{!!$Contact->email!!}</a></td>
            <td>{!!$Contact->message!!}</td>
            <td>{!! $Contact->reply !!}</td>
            <td colspan="1">
                <div class="margin-bottom-5">
                    <a href="{{route('Contact.edit',[$Contact->id])}}" class="btn btn-sm green btn-outline filter-submit margin-bottom">
                        <i class="fa fa-pencil"></i> edit</a>
                </div>
                <div class="margin-bottom-5">
                    <form method="POST" action=
                            {!!route('Contact.destroy',[$Contact->id])!!}>
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <button type="submit"  class="btn btn-sm green btn-outline filter-submit margin-bottom"><i class="fa fa-danger"></i> delete</button>
                    </form>
                </div>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/Contact/create.blade.php
 @extends('admin.layouts.layout')
 @section('title')اضافه صوره جديده@endsection
 @section('header')@endsection
 @section('content')
 <div class="row">
 <div class="col-md-12">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green">
                                        <i class="icon-pin font-green"></i>
                                        <span class="caption-subject bold uppercase"> اضافه صوره جديده</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body form">
  
                                   {{-- <form role="form" action="{{ route('Slider.store') }}" method="POST" >--}}
                                        {!! Form::open(['route'=>['Slider.store'],'method'=>'post','files'=>'true']) !!}
                                       {{--                         {{ csrf_field() }}
--}}
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@include('admin.Slider._form')
    {{--                                </form>
    --}}
                                  {!! Form::close() !!}
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                            <!-- BEGIN SAMPLE FORM PORTLET-->
   
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection

resources/views/admin/Contact/edit.blade.php
 @extends('admin.layouts.layout')
 @section('title')الرد ع رساله @endsection
 @section('header')@endsection
 @section('content')
 <div class="row">
 <div class="col-md-12">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green">
                                        <i class="icon-pin font-green"></i>
                                        <span class="caption-subject bold uppercase"> الرد ع رساله </span>
                                    </div>
                                </div>
                                <div class="portlet-body form">
  
                                        {!!Form::model($Contact,['route'=>['Contact.update',$Contact->id],'method'=>'put','files'=>'true'])!!}
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@include('admin.Contact._form')
                                    {!! Form::close() !!}
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                            <!-- BEGIN SAMPLE FORM PORTLET-->
   
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection

resources/views/admin/Contact/index.blade.php
 @extends('admin.layouts.layout')
 @section('title')الرسائل@endsection
 @section('header')@endsection
 @section('content')
                    <div class="row">
                    <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box green">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-globe"></i>الرسائل</div>
                                    <div class="tools"> </div>
                                </div>
                                <div class="portlet-body">
                                 @include('admin.Contact._table')
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection