routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index');
Auth::routes();
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('Users', 'usersController');
    Route::resource('Settings','SettingController');
    Route::resource('About','AboutController');
    Route::resource('Statistic','StatisticController');
    Route::resource('Quote','QuoteController');
    Route::resource('Slider','SliderController');
    Route::resource('Contact','ContactController');
    Route::View('/','home')->name('dashboard');
});

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $fillable = ['ar_body', 'user_id', 'en_body','en_name', 'ar_name'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public static $rules = [
        'ar_name' => 'required|string|max:191',
        'ar_body' => 'required|string',
        'en_name' => 'required|string|max:191',
        'en_body' => 'required|string'
    ];
}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use App\About;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::all();
        return View('admin.about.index', compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.about.create');
    }

    public function store(Request $request)
    {
        $requests=$request->validate(About::$rules);
        $requests['user_id']=Auth::id();
        About::create($requests);
        return redirect()->route('About.index');
    }

    public function show(About $about)
    {


    }

    public function edit($id)
    {
       $about= About::find($id);

       return view('admin.about.edit',compact('about'));

    }
    public function update(Request $request, $id)
    {
        $about=About::find($id);
        $requests=$request->validate(About::$rules);
        $about->fill($requests)->save();
        return redirect()->route('About.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $about=  About::find($id);
        if(is_null($about)){
            return back()->with('error','هذا الموضوع غير موجود');
        }
        $about->delete();
        return back()->with('success','تم الحذف ');
    }
}

resources/views/admin/about/_form.blade.php
<div class="form-body">
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('ar_name') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('ar_name',old('ar_name'),['class'=>'form-control'])!!}
        <label for="form_control_1">العنوان باللغه العربيه</label>
    </div>
    
    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('ar_body') ? ' has-error' : 'has-success' }}">
          {!!Form::textarea('ar_body',old('ar_body'),['class'=>'form-control summernote'])!!}
        <label for="form_control_1">النص  باللغه العربيه</label>
    </div>
</div>


<div class="form-body">
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('en_name') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('en_name',old('en_name'),['class'=>'form-control'])!!}
        <label for="form_control_1">العنوان  باللغه الانجليزيه</label>
    </div>

    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('en_body') ? ' has-error' : 'has-success' }}">
        {!!Form::textarea('en_body',old('en_body'),['class'=>'form-control summernote'])!!}
        <label for="form_control_1">الموضوع  باللغه الانجليزيه</label>
    </div>
</div>

<div class="form-actions noborder">
    <button type="submit" class="btn blue">حفظ</button>
    <button type="reset" class="btn default">الغاء</button>
</div>

resources/views/admin/about/_table.blade.php
<table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_3" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th class="all  text-center"> العنوان بالعربى</th>
        <th class="min-phone-l  text-center">الموضوع بالعربى</th>
        <th class="all  text-center">العنوان بالانجليزيه</th>
        <th class="min-phone-l  text-center">الموضوع بالانجليزيه</th>
        <th class="min-phone-l  text-center">الاعدادت</th>


    </tr>
    </thead>
    <tbody>
    @foreach($abouts as $about)
        <tr>
            <td>{!!$about->ar_name!!}</td>
            <td>{!!mb_substr(strip_tags($about->ar_body),0,191)!!}</td>
            <td>{!!$about->en_name!!}</td>
            <td>{!!mb_substr(strip_tags($about->en_body),0,191)!!}</td>
            <td colspan="1">
                <div class="margin-bottom-5">
                    <a href="{{route('About.edit',[$about->id])}}" class="btn btn-sm green btn-outline filter-submit margin-bottom">
                        <i class="fa fa-pencil"></i> edit</a>
                </div>

                <div class="margin-bottom-5">
                    <form method="POST" action=
                            {!!route('About.destroy',[$about->id])!!}>
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <button type="submit"  class="btn btn-sm green btn-outline filter-submit margin-bottom"><i class="fa fa-danger"></i> delete</button>

                    </form>
                </div>
            </td>

        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/about/create.blade.php
 @extends('admin.layouts.layout')
 @section('title')اضافه موضوع من نحن@endsection
 @section('header')@endsection
 @section('content')
 <div class="row">
 <div class="col-md-12">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green">
                                        <i class="icon-pin font-green"></i>
                                        <span class="caption-subject bold uppercase"> اضافه موضوع من نحن</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body form">
  
                                    <form role="form" action="{{ route('About.store') }}" method="POST">
                                                                {{ csrf_field() }}

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@include('admin.about._form')
                                    </form>
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                            <!-- BEGIN SAMPLE FORM PORTLET-->
   
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection

resources/views/admin/about/edit.blade.php
 @extends('admin.layouts.layout')
 @section('title')تعديل موضوع من نحن@endsection
 @section('header')@endsection
 @section('content')
 <div class="row">
 <div class="col-md-12">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green">
                                        <i class="icon-pin font-green"></i>
                                        <span class="caption-subject bold uppercase"> تعديل موضوع من نحن</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body form">
  
                                        {!!Form::model($about,['route'=>['About.update',$about->id],'method'=>'put'])!!}
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@include('admin.about._form')
                                    </form>
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                            <!-- BEGIN SAMPLE FORM PORTLET-->
   
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection

resources/views/admin/about/index.blade.php
 @extends('admin.layouts.layout')
 @section('title')من نحن@endsection
 @section('header')@endsection
 @section('content')
                    <div class="row">
                    <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box green">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-globe"></i>من نحن</div>
                                    <div class="tools"> </div>
                                </div>
                                <div class="portlet-body">
                                 @include('admin.about._table')
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    
                    </div>
 
@endsection
 @section('footer')@endsection