routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index');
Auth::routes();
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('Users', 'usersController');
    Route::resource('Settings','SettingController');
    Route::resource('About','AboutController');
    Route::resource('Statistic','StatisticController');
    Route::resource('Quote','QuoteController');
    Route::resource('Slider','SliderController');
    Route::resource('Contact','ContactController');
    Route::View('/','home')->name('dashboard');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;



use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [  'name', 'email', 'password','phone' ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public static $rules=[
             'name' => 'required|string|max:255',
             'email' => 'required|string|email|max:255|unique:users',
             'password' => 'required|string|min:6|confirmed',
            'phone'=>'required|numeric',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Hash;
class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::all();
        return view('admin.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
            return view('admin.users.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $requests= $request->validate(User::$rules);
       $requests['password']=Hash::make($request->password);
        $newUser=User::create($requests);
        return redirect()->route('Users.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
                    $user= User::find($id);
                    if(is_null($user)){
                        return back()->with('error','هذا العضو غير موجود');
                    }
                    return view('admin.users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $user= User::find($id);
          $rules=[
                   'name' => 'required|string|max:255',
                  'email' => 'required|string|email|max:255|unique:users,email,'.$id,
               ];
                    if(is_null($user)){
                        return back()->with('error','هذا العضو غير موجود');
                    }

                     if($request->has('password')){
                   $rules['password']=User::$rules['password'];
               }
                  $requests =  $request->validate($rules);
               if(isset($requests['password'])){
                   $requests['password']=Hash::make($requests['password']);
               }
           $update= $user->fill($requests)->save();
               return redirect()->route('Users.index')->with('success','تم التعديل بنجاح');
            }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $user=  User::find($id);
      if(is_null($user)){
          return back()->with('error','هذا العضو غير موجود');
      }
      $user->delete();
      return back()->with('success','تم حذف العضو');
    }
}

resources/views/admin/users/_form.blade.php
<div class="form-body">
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('name') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('name',old('name'),['class'=>'form-control'])!!}
        <label for="form_control_1">إسم العضو</label>
    </div>
    
    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('email') ? ' has-error' : 'has-success' }}">
        
          {!!Form::text('email',old('email'),['class'=>'form-control'])!!}
        <label for="form_control_1">البريد الالكترونى</label>
    </div>


    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('password') ? ' has-error' : 'has-success' }}">
          {!!Form::password('password',['class'=>'form-control'])!!}
        <label for="form_control_1">كلمه المرور</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('password_confirmation') ? ' has-error' : 'has-success' }}">
         {!!Form::password('password_confirmation',['class'=>'form-control'])!!}
        <label for="form_control_1">تأكيد كلمه المرور</label>
    </div>



    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('phone') ? ' has-error' : 'has-success' }}">
        {!!Form::number('phone',null,['class'=>'form-control'])!!}
        <label for="form_control_1">رقم الهاتف</label>
    </div>
</div>
<div class="form-actions noborder">
    <button type="submit" class="btn blue">حفظ</button>
    <button type="reset" class="btn default">الغاء</button>
</div>

resources/views/admin/users/create.blade.php
 @extends('admin.layouts.layout')
 @section('title')اضافه عضو@endsection
 @section('header')@endsection
 @section('content')
 <div class="row">
 <div class="col-md-12">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green">
                                        <i class="icon-pin font-green"></i>
                                        <span class="caption-subject bold uppercase"> اضافه عضو</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body form">
  
                                    <form role="form" action="{{ route('Users.store') }}" method="POST">
                                                                {{ csrf_field() }}

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@include('admin.users._form')
                                    </form>
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                            <!-- BEGIN SAMPLE FORM PORTLET-->
   
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection

resources/views/admin/users/edit.blade.php
 @extends('admin.layouts.layout')
 @section('title')اضافه عضو@endsection
 @section('header')@endsection
 @section('content')
 <div class="row">
 <div class="col-md-12">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green">
                                        <i class="icon-pin font-green"></i>
                                        <span class="caption-subject bold uppercase"> اضافه عضو</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body form">
  
                                        {!!Form::model($user,['route'=>['Users.update',$user->id],'method'=>'put'])!!}
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@include('admin.users._form')
                                    </form>
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                            <!-- BEGIN SAMPLE FORM PORTLET-->
   
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>
@endsection
 @section('footer')@endsection

resources/views/admin/users/index.blade.php
 @extends('admin.layouts.layout')
 @section('title')الاعضا@endsection
 @section('header')@endsection
 @section('content')
                    <div class="row">
                    <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box green">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-globe"></i>الاعضاء</div>
                                    <div class="tools"> </div>
                                </div>
                                <div class="portlet-body">
                                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_3" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th class="all  text-center">الاسم</th>
                                                <th class="min-phone-l  text-center">الايميل</th>
                                                <th class="min-tablet text-center" >الاعدادت</th>
                                             
                                            </tr>
                                        </thead>
                                       <tbody>
                                           @foreach($users as $user)
                                            <tr>
                                                <td>{!!$user->name!!}</td>
                                                <td>{!!$user->email!!}</td>
                                                <td colspan="1">
                                                        <div class="margin-bottom-5">
                                                            <a href="{{route('Users.edit',[$user->id])}}" class="btn btn-sm green btn-outline filter-submit margin-bottom">
                                                                <i class="fa fa-pencil"></i> edit</a>
                                                        </div>
                                                  
                                                    <div class="margin-bottom-5">
                                                    <form method="POST" action=
                                                    {!!route('Users.destroy',[$user->id])!!}>
                                                        {{ method_field('DELETE') }}
                                                         {{ csrf_field() }}
                                                        <button type="submit"  class="btn btn-sm green btn-outline filter-submit margin-bottom"><i class="fa fa-danger"></i> delete</button>
                                                        
                                                    </form>
                                                </div>
                                                </td>
                                                
                                            </tr>
                                            @endforeach
                                        </body>
                                    </table>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    
                    </div>
 
@endsection
 @section('footer')@endsection